services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app_net

  backend:
    build: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres-db:5432/mydb
      - ZAP_SCANNER_URL=http://zap-scanner:5000
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - zap-scanner
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - app_net

  login:
    build: ./login
    container_name: login
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - app_net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app_net

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 4hD@92kf!Qp7
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - app_net

  zap-scanner:
    build: ./zap-scanner
    container_name: zap-scanner
    ports:
      - "8090:8090"   # ZAP Daemon API
      - "5000:5000"   # Flask scanner API
    volumes:
      - ./reports:/reports
    restart: always
    networks:
      - app_net

  worker:
    build: ./backend
    container_name: worker
    command: ["python", "app/worker.py"]
    depends_on:
      - redis
      - backend
    environment:
      - ZAP_SCANNER_URL=http://zap-scanner:5000
    restart: always
    networks:
      - app_net
    
    volumes:
      - ./backend:/app


volumes:
  postgres-data:

networks:
  app_net:
